#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE[0]}")/.."
case $(uname -m) in
    aarch64 ) arch=amd64 ;;
    armv7l ) arch=amd64 ;;
    x86_64 ) arch=amd64 ;;
esac
dest=${1:-$arch}
case $dest in
    arm64 ) 
        platform=linux/arm64
        ext=arm64
        ;;
    arm32 ) 
        platform=linux/arm
        ext=arm32
        ;;
    amd64 ) 
        platform=linux/amd64
        ext=amd64
        ;;
    * ) 
        echo "Unknown platform"
        exit 1
        ;;
esac
docker run --platform=$platform --rm --user $(id -u):$(id -g) -v $(pwd):/uav-router uav-router_builder:$ext build