#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE[0]}")/.."
case $(uname -m) in
    aarch64 ) arch=arm64 ;;
    armv7l ) arch=arm32 ;;
    x86_64 ) arch=amd64 ;;
esac
dest=${1:-$arch}
case $dest in
    arm64 ) 
        platform=linux/arm64
        ext=arm64
        ;;
    arm32 ) 
        platform=linux/arm
        ext=arm32
        ;;
    amd64 ) 
        platform=linux/amd64
        ext=amd64
        ;;
    * ) 
        echo "Unknown platform"
        exit 1
        ;;
esac
docker run --platform=$platform --rm -v $(pwd):/uav-router uav-router_builder:$ext install dockerize --docker_dir=/uav-router/bintest/dist --prefix=/usr
cd bintest/dist
docker build --platform=$platform -t uav-router:$ext .
cd ../..
#sudo rm -rf bintest/dist