#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE[0]}")/.."

case $(uname -m) in
    aarch64 ) arch=arm64 ;;
    armv7l ) arch=arm32 ;;
    x86_64 ) arch=amd64 ;;
esac

if [ -n $1 ]; then 
    archs=(arm32 arm64 amd64)
    if [[ " ${archs[@]} " =~ " ${1} " ]]; then
        arch=$1
        shift
        echo "explicit arch $@"
    fi
fi
case $arch in
    arm64 ) 
        platform=linux/arm64
        ;;
    arm32 ) 
        platform=linux/arm
        ;;
    amd64 ) 
        platform=linux/amd64
        ;;
    * ) 
        echo "Unknown platform"
        exit 1
        ;;
esac
docker run --platform=$platform --rm --user $(id -u):$(id -g) -v $(pwd):/uav-router uav-router_builder:$arch "$@"