#!/usr/bin/env bash
set -e
script_dir=$(dirname "$(readlink -f $0)")
cd $script_dir
./waf distclean
./configure
./waf build
./image
./waf distclean
./configure arm32
./waf build
./image
./waf distclean
./configure arm64
./waf build
./image


